Repository amupedia2021/Project-Amupedia, pull requests merged in 2023-05, with the labels that each got.

#109 [GSSoC'23] Corrected typo in footer
  components/common/Footer.js
Labels: GSSoC2023

#104 Solved Issue #67 Improve Blog Card Design in Blogs Page [GSSOC'23]
  styles/scss/blogcard.module.scss
Labels: GSSoC2023

#243 Added Feature Request template
  .github/ISSUE_TEMPLATE/add_feature.yml
  .github/ISSUE_TEMPLATE/feature.yml
Labels: enhancement, GSSoC2023, 10P Points

#260 added contributors page
  components/Contributors/ContCard.js
  components/common/Navbar.js
  pages/contributors/index.js
  styles/Contributor.module.css
  styles/Navbar.module.css
  styles/scss/contributor.module.scss
Labels: enhancement, GSSoC2023, Level 3

#265 feat: add aria-label for anchor elements in footer
  components/Team/Teamcard.js
  components/common/Footer.js
Labels: enhancement, good first issue, GSSoC2023, Level 1

#291 🚀 [Feature] - Fixed the Contributors page , added pagination
  components/Testimonial/Testimonial.js
  components/common/Footer.js
  package.json
  pages/ComingSoon.js
  pages/contributors/index.js
  pages/index.js
  public/images/Fast-Time/fast-time.png
  public/images/Fast-Time/fast-time.svg
  public/images/footer/footer_2_bg.png
  public/images/footer/footer_2_bg.webp
  public/images/home/footer_2_bg.svg
  styles/Contributor.module.css
  styles/Footer.module.css
  styles/scss/contributor.module.scss
Labels: bug, enhancement, GSSoC2023, Issue by Mentors, Level 3

#295 Fixed Nav contribution Scroll effect and css fixes
  components/common/Navbar.js
  pages/index.js
  styles/Home.module.css
  styles/Navbar.module.css
Labels: bug, good first issue, GSSoC2023, Level 2

#320 Added AOS on the home page
  components/common/Footer.js
  package.json
  pages/index.js
Labels: enhancement, good first issue, GSSoC2023, Level 2

#330 Added bot to add label when PRs get create and modified issue create bot
  .github/advanced-issue-labeler.yml
  .github/workflows/add-labels.yml
  .github/workflows/issue-labeler.yml
Labels: enhancement, gssoc23, First Priority, level2

#332 Revert "Added bot to add label when PRs get create and modified issue create bot"
  .github/advanced-issue-labeler.yml
  .github/workflows/add-labels.yml
  .github/workflows/issue-labeler.yml
Labels: gssoc23

#335 Updated Styles for get in touch with us form for both mobile and pc view under the issue #113
  pages/index.js
  styles/Home.module.css
Labels: enhancement, good first issue, gssoc23, level3

#326 Resolved conflicts : Scroll To Top feature
  components/GoToTop.js
  package.json
  pages/about.js
  pages/blog/index.js
  pages/index.js
Labels: enhancement, gssoc23, level3
