Repository amupedia2021/Project-Amupedia, pull requests merged in 2023-06, with the labels that each got.

#345 Implemented new GitHub Actions workflows.
  .github/workflows/comment-on-issues.yml
  .github/workflows/comment-on-prs.yml
  styles/Home.module.css
Labels: bug, enhancement, gssoc23, First Priority

#353 Fixed Worflows of autocomment on prs
  .github/workflows/comment-on-prs.yml
Labels: bug, gssoc23

#355 Update README.md
  README.md
Labels: gssoc23

#361 added new branch ie ECE-AI
  pages/courses/btech/index.js
Labels: gssoc23, level2, futurework

#374 10 Testimonials for the website.
  components/Testimonial/data.json
Labels: gssoc23, level1

#391 enhanced navigation for articles in blog page
  pages/blog/[blogId].js
Labels: gssoc23

#386 Blog is linked
  pages/index.js
Labels: gssoc23

#349 Issue 338
  components/common/Navbar.js
  styles/Navbar.module.css
Labels: enhancement, gssoc23, level3, onhold

#436 feat: add codeql workflow
  .github/workflows/codeql.yml
Labels: gssoc23
