Repository amupedia2021/Project-Amupedia, pull requests merged in 2023-08, with the labels that each got.

#461 Logo on home page
  components/common/Navbar.js
  styles/Navbar.module.css
Labels: gssoc23

#588 Created workflow for closing stale issues
  .github/workflows/closeissues.yml
Labels: gssoc23

#590 Added Competitive Exam Section with Tables, Images, and Exam Details
  components/Curriculum/ExamCard.js
  data/examData.js
  public/images/exam/catexamszz.jpg
  public/images/exam/catfinal.jpg
  public/images/exam/cuets.jpg
  public/images/exam/download.jpg
  public/images/exam/download.png
  public/images/exam/images.jpg
  public/images/exam/matfinals.jpg
  public/images/exam/ugc.png
  public/images/exam/ugcs.png
  styles/Competitive.module.css
  styles/scss/exam.module.scss
Labels: gssoc23, level3

#597 Patched next.config.js for domain property under images section and fixed <Image> Element in index.js
  next.config.js
  package.json
  pages/_document.js
  pages/index.js
Labels: gssoc23, level3

#598 modified steps to start dev server after fixing webpack
  CONTRIBUTING.md
  README.md
Labels: gssoc23, level1

#589 Style All the Blogs
  data/blogdata.js
  pages/blog/[blogId].js
  styles/BlogDetail.module.css
Labels: gssoc23
