Repository amupedia2021/Project-Amupedia, pull requests merged in 2023-07, with the labels that each got.

#467 #463 Interview preperation section added
  pages/index.js
  pages/interviewprep/index.js
  public/images/home/interview.svg
  styles/Home.module.css
Labels: gssoc23, level3

#484 Added Relevant Content to Blog Section and Fixed Dynamic Route Refreshing Issue
  components/Blogs/BlogCard.js
  data/blogdata.js
  db/db.js
  package.json
  pages/blog/[blogId].js
  pages/blog/index.js
  public/images/blog/AICodeQuality--1-.png
  public/images/blog/aa6g894nyxxmytztd9ta.webp
  public/images/blog/cover-3.png
  public/images/blog/cover.webp
  public/images/blog/lynns-thumbnail.png
  public/images/blog/x6sc1eno6shuvql8noth.webp
Labels: gssoc23, level3

#483 Added Licenses section and badge in readme
  README.md
Labels: gssoc23

#486 Added GitHub in socials
  components/common/Footer.js
Labels: gssoc23

#462 GSSOC'23: Footer improvement
  components/common/Footer.js
  components/common/Navbar.js
  public/logomain.png
  public/logomain2.png
  styles/Footer.module.css
  styles/Navbar.module.css
Labels: gssoc23

#499 Add JS Validation on Contact Us form
  pages/index.js
  styles/Home.module.css
Labels: gssoc23

#505 Search Bar to Contributors (vaibhav-xt)
  pages/contributors/index.js
  styles/scss/contributor.module.scss
Labels: gssoc23

#512 close icon added and color of icon changed
  components/common/Navbar.js
  styles/Navbar.module.css
Labels: gssoc23, level1

#510 Added animations
  styles/Home.module.css
Labels: gssoc23

#511 check for 10 digit is applied
  pages/index.js
Labels: gssoc23

#509 [FEATURE]:Searchbar added in blog page
  components/Blogs/BlogCard.js
  pages/blog/index.js
  styles/scss/blog.module.scss
Labels: gssoc23

#514 Form responsive
  styles/Home.module.css
Labels: gssoc23

#471 #447 done (Hover on Navitem added)
  styles/Navbar.module.css
Labels: gssoc23

#529 Revert "Added animations"
  styles/Home.module.css
Labels: gssoc23

#536 server added
  server/app.js
  server/model/blog.model.js
  server/model/user.model.js
  server/package.json
  server/route/auth.route.js
  server/route/blog.route.js
  server/route/user.route.js
  utils/writeblog/disableNavbar.js
  utils/writeblog/editorUtils.js
  utils/writeblog/writeBlogUtils.js
Labels: gssoc23

#538 Btech branch/ai
  pages/courses/btech/index.js
  public/images/btech/ai.webp
  styles/Btech.module.css
Labels: gssoc23

#534 Lazy loading attribute added
  components/Blogs/BlogCard.js
  components/Contributors/ContCard.js
  components/Curriculum/ExamCard.js
  components/Curriculum/PdfShow.js
  components/Curriculum/SubjCard.js
  components/Login.js
  components/common/Navbar.js
  data/blogdata.js
  pages/blog/[blogId].js
  pages/index.js
Labels: gssoc23, level2

#533 Added aria attributes to login and contact form
  components/Login.js
  pages/index.js
Labels: gssoc23

#547 [FEATURE] Github icon in Contributors page
  components/Contributors/ContCard.js
  styles/Contributor.module.css
Labels: gssoc23, level2

#535 Added meta tags
  pages/_app.js
Labels: gssoc23

#542 Add files via upload
  components/common/Navbar.js
  pages/courses/bcom/index.js
  pages/courses/bsc/index.js
  pages/index.js
  public/images/bcom/acc.webp
  public/images/bcom/adm.webp
  public/images/bcom/bnk.webp
  public/images/bcom/com.webp
  public/images/bcom/ec.webp
  public/images/bcom/ecom.webp
  public/images/bcom/for.webp
  public/images/bcom/ins.webp
  public/images/bsc/agr.webp
  public/images/bsc/bio.webp
  public/images/bsc/chem.webp
  public/images/bsc/csc.webp
  public/images/bsc/math.webp
  public/images/bsc/nur.webp
  public/images/bsc/phy.webp
  styles/Btech.module.css
Labels: gssoc23

#556 updated contact us click
  components/common/Navbar.js
  pages/index.js
Labels: gssoc23, level1

#555 Update README.md
  README.md
Labels: gssoc23, level1

#568 Added SearchResult NotFound in Blogs and Contributors
  components/common/SearchResultNotFound.js
  pages/blog/index.js
  pages/contributors/index.js
  public/images/404/no-results.png
Labels: gssoc23

#570 fixed hamburger Icon color ✨
  components/common/Navbar.js
  styles/Navbar.module.css
Labels: gssoc23, level1

#573 added effect in OUR SERVICES section
  pages/index.js
Labels: gssoc23
